config/routes.rb
Krasaonline::Application.routes.draw do
  namespace :admin do 
  	resources :types do
  	  member do
  		  match '/add/:taxonomy_id' => 'types#add', :via => :get, :as => 'add_taxon'
  		  match '/remove/:taxonomy_id' => 'types#remove', :via => :get, :as => 'remove_taxon'
  	  end
  	  collection do
  		  post :available
  	  end
  	end
  end
  match '/type/:type' => 'types#show', :as => "set_type"
end

app/controllers/admin/types_controller.rb
class Admin::TypesController < Admin::ResourceController
  respond_to :rjs, :only => [:add, :remove]
  def new
    render :layout => !request.xhr?
  	@type = Type.new
  end
  
  def create
  	@type ||= params[:type]
  	if @type.save
  	  redirect_to :admin_types
  	else
  	  redirect_to :new_admin_type
  	end
  end

  def destroy
  	if @type.destroy
  	  flash[:notice] = I18n.t('resource_controller.successfully_removed')
  	  respond_with(@type) do |format|
          format.html { redirect_to collection_url }
          format.js   { render :partial => "/admin/shared/destroy" }
        end
  	else
  	  flash[:error] = I18n.t('errors.delete_type') 
  	  respond_with(@type) do |format|
  		format.html { redirect_to collection_url }
  	  end
  	end
  end
  
  def edit
  	@tax = @type.taxonomies
  	@products_count = Hash.new
  	@tax.each do |taxon|
  	  @products_count[taxon.root] = Product.joins(:taxons).where('taxons.parent_id' => taxon.root).count
    end
  end

  def add
	  @taxonomy = Taxonomy.find(params[:taxonomy_id])
    if @type.taxonomies << @taxonomy
      render :locals => { :taxon => @taxonomy, :product_count => Product.joins(:taxons).where('taxons.parent_id' => @taxonomy.root).count }
    else
      flash[:error] = I18n.t("errors.add_taxon_to_type")
      render :update do |p|
        p.reload
      end
    end
  rescue ActiveRecord::RecordNotFound
	  respond_with(@type) do |format|
  	  format.js { redirect_to edit_admin_type_path(@type) }
   	end
  end

  def remove
    @taxonomy = Taxonomy.find(params[:taxonomy_id])
    if @type.taxonomies.delete(@taxonomy)
      render :locals => { :taxon => @taxonomy }
    else
      flash[:error] = I18n.t("errors.remove_taxon_from_type")
      render :update do |p|
        p.reload
      end
    end
  rescue ActiveRecord::RecordNotFound
    flash[:error] = I18n.t("record_not_found", :type => 'taxon')
    redirect_to edit_admin_type_path(@type)
  end
  
  def index
    @types = Type.all
  end
  
  def available
	  @type = Type.find(params[:type])
	  @taxonomies = @type.taxonomies
    @available_taxons ||= @taxonomies.empty? ? Taxonomy.all : Taxonomy.where("id not in (?)", @taxonomies.map(&:id)).all										  
  end
end

app/controllers/types_controller.rb
class TypesController < Spree::BaseController
  respond_to :html
  
  def show
    if !Type.exists?(:permalink => params[:type])
      render_404 and return
    end
    @searcher = Spree::Search::Base.new(params)
    @products = @searcher.retrieve_products
    
    puts @products

    respond_with(@products)
  end
end

app/helpers/types_helper.rb
module TypesHelper
  def default_type
    Type.where(:first => true).first
  end
  
  def detect_type
    @action = params[:action]
    @controller = params[:controller]
    
    if @controller == 'products' and @action == 'show' and params[:id]
      Product.get_type(params[:id])
    elsif @controller == 'products' and @action == 'index'
      (!params[:search_type].blank? and params[:search_type] != 'all') ? Type.find(params[:search_type]) : default_type
    elsif @controller == 'taxons' and @action == 'show' and params[:taxon]
      Taxon.get_type(params[:taxon])
    elsif @controller == 'types' and @action == 'show' and params[:type]
      Type.find_by_permalink(params[:type])
    else 
      default_type
    end
  end
end

app/views/admin/types/_form.html.erb
<%= f.field_container :name do %>
  <%= f.label :name, t("name") %><br />
  <%= f.text_field :name %>
  <%= f.error_message_on :name %>
<% end %>

<%= f.field_container :permalink do %>
	<%= f.label :permalink, t("permalink") %><br />
	<%= f.text_field :permalink %>
	<%= f.error_message_on :permalink %>
<% end %>

<%= f.field_container :first do %>
  <%= f.label :first, t("type_first") %><br />
  <%= f.check_box :first %>
  <%= f.error_message_on :first %>
<% end %>

<h3><%= t("types") %></h3>

app/views/admin/types/_list.html.erb
<h4> Available Taxons </h4>

<table class="index" id = "active_index">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th>Amount of products in taxon</th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tax.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :sel) %>">
        <td><%= taxon.name %></td>
        <td><%= @products_count[taxon.root]%></td>        
        <td>
        	<%= link_to icon('delete') + ' ' + t("delete"),
                            remove_taxon_admin_type_path(@type, taxon), :remote => true, :class => 'iconlink', :id => 'remove_taxon' %>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/types/add.js.erb
jQuery('[id=<%= dom_id(taxon, :available) %>]').fadeOut('slow', function() { 
	$(this).remove(); 
}); 
jQuery('table#active_index tbody').append('<tr id="<%= dom_id(taxon, :sel) %>"><td><%= taxon.name %></td><td><%= product_count %></td><td><%= escape_javascript( link_to icon("delete") + " " + t("select"),
	remove_taxon_admin_type_path(@type, taxon), :remote => true, :class => "iconlink") %></td></tr>');

app/views/admin/types/available.js.erb
<script type="text/javascript">
  function displayRow(){
    var row = document.getElementById("captionRow");
    if (row.style.display == '') row.style.display = 'none';
    else row.style.display = '';
  }
</script>

<h4><%= t('available_taxons') %></h4>
<table class="index" id = "available_index">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @available_taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :available) %>">
        <td><%= taxon.name %></td>
        <td class="actions">
          <%= link_to icon('add') + ' ' + t("select"),
                            add_taxon_admin_type_path(@type, taxon),
                           :remote => true, :class => 'iconlink' %>
        </td>        
      </tr>
    <% end %>
    <% if @available_taxons.empty? %>
     <tr><td colspan="3"><%= t('no_match_found') %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/admin/types/edit.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<h1><%= t("editing_type") %></h1>

<%= render 'shared/error_messages', :target => @type %>

<%= form_for(:type, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

<%= render :partial => 'admin/types/list' %>

<button id="searchtext"><span>Get</span></button>

<%= javascript_tag do %>
  function search_for_taxons(){
    jQuery.ajax({
     data: {type: <%= @type.id %> }, 
     dataType: 'script',
     success: function(request){
       jQuery('#search_hits').html(request);
     },
     type: 'post',
     url: '<%= available_admin_types_url %>'
    });
  }

  jQuery("#searchtext").click(function () {
      search_for_taxons();
	  return false;
  });

  <% end %>
<br/>
<div id="search_hits"></div>

app/views/admin/types/index.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li id="new_type_link">
      <%= button_link_to t("new_type"), new_admin_type_url, {:remote => true, :icon => 'add', 'data-update' => 'new_type', :id => 'new_type_link'} %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("types") %></h1>

<div id="new_type"></div>

<table class="index" id='listing_types'>
  <thead>
    <tr>
      <th><%= t("name") %></th>
	  <th><%= t("type_first") %></th>
	  <th><%= t("permalink") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @types.each do |type| %>
      <tr id="<%= dom_id type %>">
        <td><%= type.name %></td>
		<td><%= type.first ? t("yes") : t("no") %></td>
		<td>/<%= type.permalink %>/</td>
		<td>
		  <%= link_to_edit(type) %>
		  &nbsp; 
		  <%= link_to_delete(type) %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/types/new.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render 'shared/error_messages', :target => @type %>

<%= form_for :type, :url => admin_types_path do |f| %>
<fieldset>
  <legend><%= t("new_type")%></legend>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons">
	<%= button t("actions.create") %>
	<%= t("or") %> <%= link_to t("actions.cancel") %>
  </p>
</fieldset>
<% end %>

app/views/admin/types/remove.js.erb
$('[id= <%= dom_id(taxon, :sel) %>]').fadeOut('slow', function() { 
	$(this).remove(); 
	return false; 
});