config/routes.rb
Krasaonline::Application.routes.draw do
  namespace :admin do 
  	resources :types do
  	  member do
  		  match '/add/:taxonomy_id' => 'types#add', :via => :get, :as => 'add_taxon'
  		  match '/remove/:taxonomy_id' => 'types#remove', :via => :get, :as => 'remove_taxon'
  	  end
  	  collection do
  		  post :available
  	  end
  	end
  end
  match '/type/:type' => 'types#show', :as => "set_type"
end

app/views/shared/_admin_type.html.erb
<%= tab(:types) %>

app/views/shared/_authentication.html.erb
<% content_for(:head) { stylesheet_link_tag('authentication') }%>
<h2><%= t(:registered_user_account) %></h2>
<%= form_for :user, :url => user_session_path do |f| %>
  <div class="password-credentials">
	<ul>
		<li>
	  		<%= content_tag(:span, t(:email)) %><br>
      		<%= f.text_field :email %>
		</li>
		<li>
	  		<%= content_tag(:span, t(:password)) %><br>
      		<%= f.password_field :password %>
		</li>
	</ul>
  </div>
<div class="remember-me">
    <label>
      <%= f.check_box :remember_me, :id => 'remember-me-checkbox' %>
      <%= content_tag :span, t('remember_me'), :id => 'remember-me-label' %>
	  <%= f.submit t(:log_in), :class => 'btn primary' %>
    </label>
<%= javascript_tag do %>
$(document).ready(function() {
	$('#remember-me-label').bind('click', function() {
		var b = $('#remember-me-checkbox');
		if(b.attr('checked')) {
			b.removeAttr('checked');
		} else {
			b.attr('checked', true);
		}
	});
});
<% end %>
</div>
  <div class="auth_links">
	<%= link_to t(:create_a_new_account), signup_path %> | <%= link_to t(:forgot_password), new_user_password_path %>
  </div>
<% end %>

app/views/shared/_bestseller.html.erb
<p><%= bestseller.name %> - <%= bestseller.price %></p>

app/views/shared/_cart_block.html.erb
# spree ajax cart implementation todo
# http://github.com/pogodan/spree_ajax_cart

app/views/shared/_categories.html.erb
<% if current_page? (:controller => 'products', :action => 'show') %>
  
<% elsif current_page? (:controller => 'types', :action => 'show') %>
  
<% else %> 
  
<% end %> 

app/views/shared/_delivery.html.erb
<%= content_tag :div, :id => 'delivery' do -%>
	<%= link_to 'Delivery', '#' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div id="errorExplanation" class="errorExplanation">
    <h2><%= t(:errors_prohibited_this_record_from_being_saved, :count => target.errors.count) %>:</h2>
    <p><%= t(:there_were_problems_with_the_following_fields) %>:</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_guest_checkout.html.erb
<div class="guest_checkout">
 	<%= render 'shared/error_messages', :target => @order %>
  	<h2><%= t(:guest_user_account) %></h2>
   	<%= form_for @order, :url => update_checkout_registration_path, :html => { :method => :put, :id => 'checkout_form_registration'} do |f| %>
    	<ul>
			<li>
				<%= content_tag(:span, t(:email)) %><br>
       			<%= f.text_field :email %>
			</li>
		</ul>
		<%= f.submit t(:continue), :class => 'btn primary' %>
  	<% end %>
</div>

app/views/shared/_login_bar.html.erb
<% if current_user %>
	<%= content_tag :div, :id => 'sidebar_login' do -%>
		<%= link_to t('my_account'), account_path %>
		<%= link_to t('logout'), destroy_user_session_path %>
	<% end %>
<% else %>
	<%= content_tag :div, :id => 'sidebar_login' do -%>
		<%= link_to t('log_in'), login_path %>
	<% end %>
<% end %>

app/views/shared/_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= content_tag(:span, t(:no_products_found), :id => 'search_results_not_found') %>
<% elsif params.key?(:keywords) %>
  <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
<% end %>
 
<% if products.any? %>
  <% products.each do |product| %>
	<div id = "product_<%= product.id %>" class="product_item">
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
          <%= link_to small_image(product, :class => 'product-small-image'), product %>
          <%= link_to raw(product.name), product, :class => 'product-title' %>
		  <%= content_tag(:div, :class => 'product-price') do -%>
		  	<span class="price"><%= product_price(product) -%></span>
	 	  <% end %>
	      <% if product.has_variants? %>
			<% form_for :order, :url => populate_orders_url do |f| %>
				<% @variants = product.variants.map { |v| [v.options_text, "#{v.id}, 1"] } %>
				<%= select_tag("var", options_for_select(@variants)) %>
				<%= image_submit_tag("layout/cart.png", :class => 'add_to_cart_button') %>
			<% end %>
		  <% end %>
    <% end %>
	</div>
  <% end %>
<% end %>
  
<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)
      
%><%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<% end %>

app/views/shared/_rightbar.html.erb
<table>
	<tr>
		<td>
			<%= image_tag('layout/key.png') %>
		</td>
		<td id="sidebar-first">
			Вход для клиентов
		</td>
	</tr>
	<tr>
		<td>
			<%= image_tag('layout/basket.png')%>
		</td>
		<td id="sidebar-first">
			Корзина
		</td>
	</tr>
	<tr>
		<td>
			<span id="sidebar">
				<strong>Товаров: </strong>
			</span>
			<span id="sidebargr">123 шт.</span>
		</td>
	</tr>
	<tr>
		<td>
			<span id="sidebar">
				<strong>Сумма: </strong>
			</span>
			<span id="sidebargr">1222.00 грн.</span>
		</td>
	</tr>
	<tr>
		<td colspan="2" align="center">
			<%= image_tag('layout/oformit.png') %>
		</td>
	</tr>
	<tr>
		<td>
			<%= image_tag('layout/phone.png') %>
		</td>
		<td id="phone">
			<span>
				<strong>Телефоны: </strong>
			</span>
		</td>
	</tr>
	<tr>
		<td class="menutitle">
			<span id="sidebarphone">(066)</span>
			<span id="sidebargr">757-08-06</span>
		</td>
	</tr>
	<tr>
		<td class="menutitle">
			<span id="sidebarphone">(057)</span>
			<span id="sidebargr">762-81-01</span>
		</td>
	</tr>
	<tr>
		<td>
			<% image_tag('layout/icq.png') %>
		</td>
		<td>
			<span id="sidebarphone">ICQ</span>
			<span id="sidebargr"> 7757097</span>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="menutitle1">
			<span>Действие феромонов</span>
		</td>
	</tr>
	<tr>
		<td colspan="2" id="sidebar1">
			<strong>Духи с феромонами</strong> - это безусловно лучшее современное средство способное влиять на сексуальное поведение других людей.<br /><i>Они позволят вам:</i><br /><i>— проще знакомиться с девушкой или парнем</i><br /><i>— максимально повысить свою сексуальную привлекательность</i><br /><i>— существенно увеличить количество сексуальных партнеров</i>
<br /><br />В нашем магазине <strong>KrasaOnline</strong> пердложены следующие товары: средства для ухода за кожей, волосами, ногтями; декоративная косметика; парфюмерия. И всё это с доставкой на дом. Вам остается лишь выбрать понравившиеся товары и заказать через "корзину".
		</td>
	</tr>
</table>

app/views/shared/_search.html.erb
<% @types = Type.all %>
<%= form_tag products_url, :method => :get, :id => 'search' do %>
  <%= content_tag(:span, t('search'), :id => 'search_form_label') %>
  <%= content_tag(:div, text_field_tag(:keywords, params[:keywords]), :class => "search_form_keywords") %> 
  <%= select_tag :search_type, 
        options_for_select([[t(:all_departments), 'all']] + @types.map {|t| [t.name, t.id]}), :id => 'search_form_type_options' %>
  <%= submit_tag '',:name => nil, :id => 'search_form_submit' %>
<% end %>
<%= content_tag :div, :id => 'search_example' do %>
Например, <%= link_to 'феромоны мужские', '', :id => 'search_example_link' %>
<% end %>

<%= javascript_tag do %>
	$("#search_example_link").click(function() { 
		$(this).animate({
			opacity: 'toggle',
		}, 150, function() { $(this).animate({opacity: 'toggle',}, 150); }); 
	});
<% end %>

app/views/shared/_taxonomies.html.erb
<div>
  <% get_current_menu.each do |taxonomy| %>
	<dl class="navigation">
		<dt>
        	<%= link_to t("shop_by_taxonomy", :taxonomy => taxonomy.name.singularize), seo_url(taxonomy.root) %>
		</dt>
      	<% taxonomy.root.children.each do |taxon| %>
         <dd>
		 	<% if @taxon and ([@taxon] + @taxon.ancestors).include?(taxon) %>
         		<%= link_to taxon.name, seo_url(taxon), :class => 'current' %>
			<% else %>
				<%= link_to taxon.name, seo_url(taxon) %>
			<% end %>
		 </dd>
        <% end %>
      </dl>
  <% end %>
</div>

app/views/shared/_type_menu.html.erb
<div class="grid_4 logo"><%= link_to image_tag('layout/logo.png'), root_url %></div>
<div class="grid_7 types">
	<div class="type"><%= link_to image_tag('layout/duxi.png'), set_type_url('main') %><span>Духи с феромонами</span></div>
	<div class="type"><%= link_to image_tag('layout/kosmetika.png'), set_type_url('cosmetika') %><span>Косметика</span></div>
	<div class="type"><%= link_to image_tag('layout/parfum.png'), set_type_url('fieromony') %><span>Парфюмерия</span></div>
</div>